### ISSUE TITLE
Asymptotes only appear with Special Angles

### ISSUE THREAD

**Issue by elisemorgan** [phetsims/trig-lab#10]
Test device: iPad 2

Operating System: iOS 8.3

Browser: Safari

Problem description: The asymptotes for the tan graph seem inconsistent because I'm not moving the cursor on the graph at all but the asymptote don't show until I select Special Angles. 

Steps to reproduce: Move cursor to where asymptote should be. Observe that none is shown. Select Special Angles and the asymptote line appears.

Severity: Minor. This may be more of a design decision.

Screenshots: 
![image 6](https://cloud.githubusercontent.com/assets/12610678/8917272/4a388a82-346e-11e5-847b-d831c55379c3.jpg)
![image 7](https://cloud.githubusercontent.com/assets/12610678/8917276/54b89e7a-346e-11e5-9e3f-57806244521f.jpg)

Troubleshooting information (do not edit):
Name: ‪Trig Lab‬
URL: http://www.colorado.edu/physics/phet/dev/html/trig-lab/1.0.0-dev.14/trig-lab_en.html
Version: 1.0.0-dev.14 2015-07-23 21:40:49 UTC
Features missing: fullscreen
User Agent: Mozilla/5.0 (iPad; CPU OS 8_3 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12F69 Safari/600.1.4
Language: en-us
Window: 1024x671
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 IMGSGX543-115.5)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.00)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 8 uniform: 128
Texture: size: 4096 imageUnits: 8 (vertex: 8, combined: 8)
Max viewport: 4096x4096
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"858e65ac","branch":"master"},"axon":{"sha":"579f8c66","branch":"master"},"babel":{"sha":"2431e711","branch":"master"},"brand":{"sha":"3c45cb6f","branch":"phet"},"chipper":{"sha":"b737909c","branch":"master"},"dot":{"sha":"e34c6b2c","branch":"master"},"joist":{"sha":"35a12c18","branch":"master"},"kite":{"sha":"24978146","branch":"master"},"phet-core":{"sha":"8e31808c","branch":"master"},"phetcommon":{"sha":"89a44d2c","branch":"master"},"scenery":{"sha":"24a4d9ab","branch":"master"},"scenery-phet":{"sha":"f3f30545","branch":"master"},"sherpa":{"sha":"b1ce7789","branch":"master"},"sun":{"sha":"dc08e5f3","branch":"master"},"trig-lab":{"sha":"f6cb7179","branch":"master"}}

**Comment by amanda-phet** [comment]
@elisemorgan that is true that this was a design decision. It IS possible to get the asymptote when not using special angles, but because it has to be precise it can be difficult!
