### ISSUE TITLE
AquaRadioButtons have ceased functioning

### ISSUE THREAD

**Issue by samreid** [phetsims/trig-lab#4]
After https://github.com/phetsims/chipper/commit/a282938be9077a980309b1330b9084e5e6c95e08 the radio button ceased functioning.  @samreid investigated in https://github.com/phetsims/chipper/issues/161 and suggested the problem may be due to:

> So I suspect that logic code in trig lab is doing === comparisons on internationalized strings to determine whether to show the sin/cos/tan and degree/radian. This will be a problem since those strings will be different in every language.

So if this indeed the problem, we should switch to non-interationalized strings for choosing between tan/sin/cos/degrees/radians.

@dubson can you take it from here?

**Comment by dubson** [comment]
Yes, my code contains comparisons like graph === ‘cos’   but how can the String ‘cos’ get confused with my internationalized string for ‘cos’ which is

var cosStr = require( 'string!TRIG_LAB/cos' );

**Comment by samreid** [comment]
For example, you will have to change:

```js
    var cosRadioButton = new AquaRadioButton( properties.graphProperty, cosStr, cosText, myRadioButtonOptions );
    var sinRadioButton = new AquaRadioButton( properties.graphProperty, sinStr, sinText, myRadioButtonOptions );
    var tanRadioButton = new AquaRadioButton( properties.graphProperty, tanStr, tanText, myRadioButtonOptions );

```

to

```js
    var cosRadioButton = new AquaRadioButton( properties.graphProperty, 'cos', cosText, myRadioButtonOptions );
    var sinRadioButton = new AquaRadioButton( properties.graphProperty, 'sin', sinText, myRadioButtonOptions );
    var tanRadioButton = new AquaRadioButton( properties.graphProperty, 'tan', tanText, myRadioButtonOptions );
```

That 2nd arg should be the property value, not the internationalized string text.  Probably same error for the units radio buttons.

**Comment by jonathanolson** [comment]
First, I wouldn't rely on a translated string being anything particular in the code. Someone could translate it to a capitalized "Cos", and the comparison would be bad.

Second, string lookups (require statements for string!) now don't equal the exact values from the translation files, since it pads them with Unicode embedding marks so that LTR/RTL order is maintained even if LTR/RTL strings are combined into one Text.

**Comment by dubson** [comment]
I see.  Thanks!!  I will correct my code.  Does seem like a future time bomb though.

**Comment by dubson** [comment]
Understood, and I agree.  I withdraw my 'time bomb' remark.

**Comment by dubson** [comment]
Issue resolved.  Plane crashed due to pilot error.  Pilot has been re-trained:
Never use internationalized strings in logic code.
